#!/usr/bin/env bash
# Compose ~/.claude/output-styles/default.md from skill sources.
#
# Usage: compose-output-style.sh SKILL [SKILL ...]
#
# Each SKILL is a name under ~/.claude/skills/NAME/SKILL.md.
# YAML frontmatter is stripped from each skill before inclusion.
#
# Re-run any time skills change. Output takes effect on next session.

set -euo pipefail

SKILLS_DIR="$HOME/.claude/skills"
OUTPUT_FILE="$HOME/.claude/output-styles/default.md"

if [[ $# -eq 0 ]]; then
    echo "Usage: $(basename "$0") SKILL [SKILL ...]" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Strip YAML frontmatter (content between opening --- and closing ---)
strip_frontmatter() {
    awk '
        /^---$/ && !in_front && !done { in_front=1; next }
        /^---$/ && in_front           { in_front=0; done=1; next }
        !in_front                     { print }
    '
}

{
    cat <<'EOF'
---
name: default
description: Active output style (generated by compose-output-style.sh)
keep-coding-instructions: true
---

EOF

    for name in "$@"; do
        src="$SKILLS_DIR/$name/SKILL.md"
        if [[ ! -f "$src" ]]; then
            echo "Error: skill '$name' not found at $src" >&2
            exit 1
        fi
        strip_frontmatter < "$src"
        echo
    done
} > "$OUTPUT_FILE"

echo "Written: $OUTPUT_FILE"
