#!/usr/bin/env bash
# Compose ~/.claude/output-styles/default.md from arbitrary .md sources.
#
# Usage: compose-output-style.sh PATH [PATH ...]
#
# Each PATH is relative to ~/.claude/. Examples:
#   skills/caveman/SKILL.md
#   style/only-use-typeable-characters.md
#
# YAML frontmatter (if present) is stripped from each source before inclusion.
#
# Re-run any time sources change. Output takes effect on next session.

set -euo pipefail

CLAUDE_DIR="$HOME/.claude"
OUTPUT_FILE="$CLAUDE_DIR/output-styles/default.md"

if [[ $# -eq 0 ]]; then
    echo "Usage: $(basename "$0") PATH [PATH ...]" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Strip YAML frontmatter (content between opening --- and closing ---)
# No-op for files without frontmatter.
strip_frontmatter() {
    awk '
        /^---$/ && !in_front && !done { in_front=1; next }
        /^---$/ && in_front           { in_front=0; done=1; next }
        !in_front                     { print }
    '
}

{
    cat <<'EOF'
---
name: default
description: Active output style (generated by compose-output-style.sh)
keep-coding-instructions: true
---

EOF

    for relpath in "$@"; do
        src="$CLAUDE_DIR/$relpath"
        if [[ ! -f "$src" ]]; then
            echo "Error: source not found at $src" >&2
            exit 1
        fi
        strip_frontmatter < "$src"
        echo
    done
} > "$OUTPUT_FILE"

echo "Written: $OUTPUT_FILE"
