#!/usr/bin/env bash
# Compose ~/.claude/output-styles/default.md from skill and module sources.
#
# Usage: compose-output-style.sh skill:caveman module:flag-assumptions ...
#
# Sources:
#   skill:NAME  -- reads ~/.claude/skills/NAME/SKILL.md, strips YAML frontmatter
#   module:NAME -- reads ~/.claude/output-style-modules/NAME.md as-is
#
# Re-run any time skills or modules change. Output takes effect on next session.

set -euo pipefail

SKILLS_DIR="$HOME/.claude/skills"
MODULES_DIR="$HOME/.claude/output-style-modules"
OUTPUT_FILE="$HOME/.claude/output-styles/default.md"

if [[ $# -eq 0 ]]; then
    echo "Usage: $(basename "$0") skill:NAME|module:NAME [...]" >&2
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Strip YAML frontmatter (content between opening --- and closing ---)
strip_frontmatter() {
    awk '
        /^---$/ && !in_front && !done { in_front=1; next }
        /^---$/ && in_front           { in_front=0; done=1; next }
        !in_front                     { print }
    '
}

{
    cat <<'EOF'
---
name: default
description: Active behavioral modules (generated by compose-output-style.sh)
keep-coding-instructions: true
---

EOF

    for arg in "$@"; do
        type="${arg%%:*}"
        name="${arg#*:}"

        case "$type" in
            skill)
                src="$SKILLS_DIR/$name/SKILL.md"
                if [[ ! -f "$src" ]]; then
                    echo "Error: skill '$name' not found at $src" >&2
                    exit 1
                fi
                strip_frontmatter < "$src"
                echo
                ;;
            module)
                src="$MODULES_DIR/$name.md"
                if [[ ! -f "$src" ]]; then
                    echo "Error: module '$name' not found at $src" >&2
                    exit 1
                fi
                cat "$src"
                echo
                ;;
            *)
                echo "Error: unknown source type '$type' (use skill: or module:)" >&2
                exit 1
                ;;
        esac
    done
} > "$OUTPUT_FILE"

echo "Written: $OUTPUT_FILE"
